language: node_js
node_js: stable
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - CXX=g++-4.8
  - secure: 1qNAGvTxwjhm4sis4WweMOz3KT4721oJYyL9LhrKrEwy+DAf0ARC2pH7NqhccqPtYSi+7qkpa7/4UroPSUHAsZOgAYsRqzhqhurQKpljsckAG7JUo79kggSAampcZCBxTmsrIfiBRhmkl7ifbb4pbaJsFwQwAulBMloAEkw96NtA53wnn8hrOguGDaM3vilBvwoWr2jO8Nff2DWMTLNar6cZh901ND6LszBWcvhzfaqtQB4jrKteXwgRF6R+u1JIvS7g7F3o8yveeXfizbrkyJucPhCV7Gn6cCP3PGnryOXcOz7Md4xQGZkDcuYNWy0UYIzRMunV+TPIFvCxilCu8NsDTf4+DssbyqCq/tK3/VKRclC7a+vx1ysq1h6AKh9LF7CbVh4HcDtnbKETPesOPpq/qTEifDrtk+QGc2plM0PlzWhLq5AWnIM6lhkskD2YGyW80xrWXquhsTlUnNVy/m9/jHQiO3DyPYEEBSTQXIdi6lM2uO5baMBb53kRV7n6S/tPvu17cncK80c3Tyhc9W5guqf55rXLxPAdCuoFZae/xSLNVykl3RTDy8lFAsxZgJ8Fr1ehZTHJ09gODqsY81YEh+cZVFWdjkfqhOKSpfY+tyI+GZ+dnM4lYf0G6nUWO0ttlOVEHRGwPigrVcRL0NPyJjWz8N/BuOXyuiMzIzc=
dd:
  secure: UHMWPr8P9YIMBrpJUEy9iBs7d1uXPs3UVboKwEtUuf74Q5GW2DubeYpJkAY3kv3JZ/XalJ7PhxuYBbLhLkQ82jZ08kDdWHMkjaYqs5MdZrDcwwYlHQ9xa0gx2FoeuAYgFhpSEZqZ310oLIEkO98ELv+6vJ7711I8jCbQWY/KsOpMWEu3LkO6KWawf4FGmAKyoAezSYritdzvk12cXsDNh/g84FJIRFFUU8KrWX04UK5rDOdXMw6y+1oi0oRftBZgYYDriOMnAJR/fj16nIySN2GUWYyyEgk6/0TjTi2XRaIFEVzFH7Nh47eWJpCnsgTIuZBtBqkKyZ0834WH5xjgbDbXCaA7WQRKw22qtlYaz0fHf/lxbPv/KI8XbodA2ohq0uLl5L1PqpTCulzbVoAvTJskNaT1IWX+mxfJRHpZEokGphLp+NwpDGgjOFKEXKe/7adRUDx1/XsCKxWSE3m4H5UUX8MbHYLlPZvVpB/LiGcME9ky6r+j9Ih/VbZny9QJwDlXu+vhyaknnz4vsBhkocqRaGwZQyYGyoyhE4/q7NJAmCyjNTL35KfzQUYFMWmcBliWCLfGRnL5dcAGtgZHAs2Zs0BeTj1DXL7vVgZ84TC9Q8dFXFoxmDUrajEnFeTMZJ6B6V2qABiQ43uLY2aNQzZa4Mx8RbC8LuuI8jCGTVc=
